server:
  port: 8082

spring:
  application:
    name: orders-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/perfumeria}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driverClassName: org.postgresql.Driver
    hikari:
      data-source-properties:
        prepareThreshold: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: orders_schema
    open-in-view: false
